name: e2e Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Yarn Modules
        uses: c-hive/gha-yarn-cache@v2
        with:
          directory: test-e2e
      - name: Install modules
        run: yarn --frozen-lockfile
        working-directory: test-e2e

  typescript-stack:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Yarn Modules
        uses: c-hive/gha-yarn-cache@v2
        with:
          directory: test-e2e
      - name: Install modules
        run: yarn --frozen-lockfile
        working-directory: test-e2e
      - name: Install Docker
        uses: docker-practice/actions-setup-docker@master
      # Install CLI
      - name: Install CLI and deps
        run: npm install -g @nitric/cli@rc-latest start-server-and-test
      - name: Run Tests
        run: start-server-and-test 'nitric run --ci' tcp:49152 'yarn --cwd ../test-e2e test'
        working-directory: typescript-stack

  python-stack:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Yarn Modules
        uses: c-hive/gha-yarn-cache@v2
        with:
          directory: test-e2e
      - name: Install modules
        run: yarn --frozen-lockfile
        working-directory: test-e2e
      - name: Install Docker
        uses: docker-practice/actions-setup-docker@master
      # Install CLI
      - name: Install CLI and deps
        run: npm install -g @nitric/cli@rc-latest start-server-and-test
      - name: Run Tests
        run: start-server-and-test 'nitric run --ci' tcp:49152 'yarn --cwd ../test-e2e test'
        working-directory: python-stack

  go-stack:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Yarn Modules
        uses: c-hive/gha-yarn-cache@v2
        with:
          directory: test-e2e
      - name: Install modules
        run: yarn --frozen-lockfile
        working-directory: test-e2e
      - name: Install Docker
        uses: docker-practice/actions-setup-docker@master
      # Install CLI
      - name: Install CLI and deps
        run: npm install -g @nitric/cli@rc-latest start-server-and-test
      - name: Run Tests
        run: start-server-and-test 'nitric run --ci' tcp:49152 'yarn --cwd ../test-e2e test'
        working-directory: go-stack

  java-stack:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Yarn Modules
        uses: c-hive/gha-yarn-cache@v2
        with:
          directory: test-e2e
      - name: Install modules
        run: yarn --frozen-lockfile
        working-directory: test-e2e
      - name: Install Docker
        uses: docker-practice/actions-setup-docker@master
      # Install CLI
      - name: Install CLI and deps
        run: npm install -g @nitric/cli@rc-latest start-server-and-test
      - name: Run Tests
        run: start-server-and-test 'nitric run --ci' tcp:49152 'yarn --cwd ../test-e2e test'
        working-directory: java-stack

  java-stack-multi:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Yarn Modules
        uses: c-hive/gha-yarn-cache@v2
        with:
          directory: test-e2e
      - name: Install modules
        run: yarn --frozen-lockfile
        working-directory: test-e2e
      - name: Install Docker
        uses: docker-practice/actions-setup-docker@master
      # Install CLI
      - name: Install CLI and deps
        run: npm install -g @nitric/cli@rc-latest start-server-and-test
      - name: Run Tests
        run: start-server-and-test 'nitric run --ci' tcp:49152 'yarn --cwd ../test-e2e test'
        working-directory: java-stack-multi
